// packages/frameworks/solid/src/components/ui/accordion.tsx
import {
	Accordion as ArkAccordion,
	type AccordionItemProps,
	type AccordionItemTriggerProps,
	type AccordionItemContentProps,
} from "@ark-ui/solid";
import { splitProps } from "solid-js";
import { cn } from "../../lib/utils";
import { ChevronDown } from "lucide-solid";
import { createSignal, onMount } from "solid-js";

export interface AccordionContentProps extends AccordionItemContentProps {
	id: string;
}

const Accordion = ArkAccordion.Root;

const AccordionItem = (props: AccordionItemProps) => {
	const [, rest] = splitProps(props, ["class"]);
	return <ArkAccordion.Item class={cn("border-b", props.class)} {...rest} />;
};

const AccordionTrigger = (props: AccordionItemTriggerProps) => (
	<div class="flex">
		<ArkAccordion.ItemTrigger
			class={cn(
				"flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180",
				props.class,
			)}
		>
			{props.children}
			<ChevronDown class="h-4 w-4 shrink-0 transition-transform duration-400 rotate-0" />
		</ArkAccordion.ItemTrigger>
	</div>
);

const AccordionContent = (props: AccordionContentProps) => {
	const [rect, setRect] = createSignal({ height: 0, width: 0 });

	let resizeObserver: ResizeObserver;

	/**
	 * 16 accounts for the padding pixels below the AccordianItem which is
	 * required for the dropdown animation to function correctly.
	 *
	 * TODO: If someone overrides the padding, I need to dynamically pull in
	 * that value for the `adjustedHeight`
	 */
	const handler = (entries: ResizeObserverEntry[]) => {
		const { height, width } = entries[0].contentRect;
		const adjustedHeight = height + 16;
		setRect({ height: adjustedHeight, width });
	};
	onMount(() => {
		const targetDiv = document.getElementById(props.id);
		if (targetDiv) {
			resizeObserver = new ResizeObserver(handler);
			resizeObserver.observe(targetDiv);
		}

		return () => {
			if (resizeObserver) resizeObserver.disconnect();
		};
	});

	return (
		<ArkAccordion.ItemContent
			class={cn(
				"animate-accordion-up overflow-hidden text-sm transition-all data-[state=open]:animate-accordion-down",
				props.class,
			)}
			style={{ "--accordion-content-height": `${rect().height}px` }}
		>
			<div id={props.id} class="pb-4 pt-0">
				{props.children}
			</div>
		</ArkAccordion.ItemContent>
	);
};

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };

// packages/frameworks/react/src/components/ui/accordion.tsx
import type { CSSProperties } from 'react'
import React, { useRef, useEffect, useState } from 'react'
import {
  Accordion as ArkAccordion,
  type AccordionItemProps,
  type AccordionItemTriggerProps,
  type AccordionItemContentProps,
} from '@ark-ui/react'
import { ChevronDown } from 'lucide-react'
import { cn } from '../../lib/utils'

const Accordion = ArkAccordion.Root

const AccordionItem = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.Item>,
  AccordionItemProps
>((props, ref) => {
  const { className, ...restProps } = props
  return <ArkAccordion.Item ref={ref} className={cn('border-b', className)} {...restProps} />
})
AccordionItem.displayName = 'AccordionItem'

const AccordionTrigger = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.ItemTrigger>,
  AccordionItemTriggerProps
>(({ className, children, ...props }, ref) => (
  <div className="flex">
    <ArkAccordion.ItemTrigger
      ref={ref}
      className={cn(
        'flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180',
        className,
      )}
      {...props}
    >
      {children}
      <ChevronDown className="w-4 h-4 transition-transform duration-200 shrink-0" />
    </ArkAccordion.ItemTrigger>
  </div>
))
AccordionTrigger.displayName = 'AccordionTrigger'

const AccordionContent: React.FC<AccordionItemContentProps> = ({ id, className, children }) => {
  const [rect, setRect] = useState<{ height: number; width: number }>({
    height: 0,
    width: 0,
  })
  const contentRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handler = (entries: ResizeObserverEntry[]) => {
      const { height } = entries[0].contentRect
      const adjustedHeight = height + 16
      setRect((prevRect) => ({ ...prevRect, height: adjustedHeight }))
    }

    const resizeObserver = new ResizeObserver(handler)

    if (contentRef.current) {
      resizeObserver.observe(contentRef.current)
    }
    return () => {
      resizeObserver.disconnect()
    }
  }, [])

  const style: CSSProperties = {
    '--accordion-content-height': `${rect.height}px`,
  } as React.CSSProperties

  return (
    <ArkAccordion.ItemContent
      className={cn(
        'animate-accordion-up overflow-hidden text-sm transition-all',
        'data-[state=open]:animate-accordion-down',
        className,
      )}
      style={style}
    >
      <div ref={contentRef} id={id} className="pt-0 pb-4">
        {children}
      </div>
    </ArkAccordion.ItemContent>
  )
}
AccordionContent.displayName = 'AccordionContent'

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent }
