// packages/frameworks/vue/src/components/ui/Accordion.vue
<script setup lang="ts">
import { ref, nextTick, watch } from 'vue';
import { Accordion, AccordionItem, AccordionItemTrigger, AccordionItemContent } from '@ark-ui/vue';
import { ChevronDown } from 'lucide-vue-next';

const items = ref(['React', 'Solid', 'Vue']);
// Store active item index and content heights
const activeItem = ref(null);
const contentHeights = ref(items.value.map(() => '0px'));

// Watch for changes in active item and update height
watch(activeItem, async (newIndex) => {
  await nextTick(); // Wait for DOM update
  contentHeights.value = contentHeights.value.map((_, index) =>
    index === newIndex ? `${document.getElementById(`content-${index}`).scrollHeight}px` : '0px'
  );
});
</script>

<template>
  <div class="max-w-md mx-auto mt-10">
    <Accordion.Root collapsible v-model="activeItem">
      <Accordion.Item v-for="(item, index) in items" :key="item" :value="index" class="border-b">
        <div class="flex">
          <Accordion.ItemTrigger
            class="flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180">
            What is {{ item }}?
            <ChevronDown class="h-4 w-4 shrink-0 transition-transform duration-200" />
          </Accordion.ItemTrigger>
        </div>
        <Accordion.ItemContent :id="`content-${index}`"
          class="overflow-hidden text-sm transition-all data-[state=open]:animate-accordion-down"
          :style="{ 'max-height': contentHeights[index] }">
          <div class="pb-4 pt-0">
            {{ item }} is a JavaScript library for building user interfaces.
          </div>
        </Accordion.ItemContent>
      </Accordion.Item>
    </Accordion.Root>
  </div>
</template>

// packages/frameworks/react/src/components/ui/accordion.tsx
import type { CSSProperties } from 'react'
import React, { useRef, useEffect, useState } from 'react'
import {
  Accordion as ArkAccordion,
  type AccordionItemProps,
  type AccordionItemTriggerProps,
  type AccordionItemContentProps,
} from '@ark-ui/react'
import { ChevronDown } from 'lucide-react'
import { cn } from '../../lib/utils'

const Accordion = ArkAccordion.Root

const AccordionItem = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.Item>,
  AccordionItemProps
>((props, ref) => {
  const { className, ...restProps } = props
  return <ArkAccordion.Item ref={ref} className={cn('border-b', className)} {...restProps} />
})
AccordionItem.displayName = 'AccordionItem'

const AccordionTrigger = React.forwardRef<
  React.ElementRef<typeof ArkAccordion.ItemTrigger>,
  AccordionItemTriggerProps
>(({ className, children, ...props }, ref) => (
  <div className="flex">
    <ArkAccordion.ItemTrigger
      ref={ref}
      className={cn(
        'flex flex-1 items-center justify-between py-4 font-medium transition-all hover:underline [&[data-state=open]>svg]:rotate-180',
        className,
      )}
      {...props}
    >
      {children}
      <ChevronDown className="w-4 h-4 transition-transform duration-200 shrink-0" />
    </ArkAccordion.ItemTrigger>
  </div>
))
AccordionTrigger.displayName = 'AccordionTrigger'

const AccordionContent: React.FC<AccordionItemContentProps> = ({ id, className, children }) => {
  const [rect, setRect] = useState<{ height: number; width: number }>({
    height: 0,
    width: 0,
  })
  const contentRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handler = (entries: ResizeObserverEntry[]) => {
      const { height } = entries[0].contentRect
      const adjustedHeight = height + 16
      setRect((prevRect) => ({ ...prevRect, height: adjustedHeight }))
    }

    const resizeObserver = new ResizeObserver(handler)

    if (contentRef.current) {
      resizeObserver.observe(contentRef.current)
    }
    return () => {
      resizeObserver.disconnect()
    }
  }, [])

  const style: CSSProperties = {
    '--accordion-content-height': `${rect.height}px`,
  } as React.CSSProperties

  return (
    <ArkAccordion.ItemContent
      className={cn(
        'animate-accordion-up overflow-hidden text-sm transition-all',
        'data-[state=open]:animate-accordion-down',
        className,
      )}
      style={style}
    >
      <div ref={contentRef} id={id} className="pt-0 pb-4">
        {children}
      </div>
    </ArkAccordion.ItemContent>
  )
}
AccordionContent.displayName = 'AccordionContent'

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent }
