// packages/frameworks/solid/src/components/ui/label.tsx
import type { Component, ComponentProps } from "solid-js";
import { splitProps } from "solid-js";
import { ark } from "@ark-ui/solid";
import { cva } from "class-variance-authority";
import { cn } from "../../lib/utils";

const labelVariants = cva(
	"text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
);

const Label: Component<ComponentProps<"label">> = (props) => {
	const [, rest] = splitProps(props, ["class"]);
	return (
		<ark.label class={cn(labelVariants(), props.class)} {...rest}>
			{props.children}
		</ark.label>
	);
};

export { Label, labelVariants };

// packages/frameworks/react/src/components/ui/label.tsx
import React, { ForwardedRef } from 'react'
import { cva } from 'class-variance-authority'
import { cn } from '../../lib/utils'

const labelVariants = cva(
  'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
)

interface LabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  children: React.ReactNode
}

const Label = React.forwardRef<HTMLLabelElement, LabelProps>(
  ({ className, children, ...props }, ref) => (
    <label ref={ref} className={cn(labelVariants(), className)} {...props}>
      {children}
    </label>
  ),
)

Label.displayName = 'Label'

export { Label, labelVariants }
